# Generated by Django 6.0.7 on 2026-07-13 01:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VaultUser',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('salt', models.BinaryField()),
                ('auth_verifier', models.BinaryField()),
                ('encrypted_vault_key', models.BinaryField()),
                ('public_key', models.BinaryField()),
                ('encrypted_private_key', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VaultEntry',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('encrypted_data', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(db_column='owner_id', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='vault.vaultuser')),
            ],
            options={
                'db_table': 'vault_entries',
                'ordering': ['-updated_at'],
            },
        ),
    ]
